version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg:
    image: postgres:14-alpine3.17
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PG_DSN: ${PG_DSN}

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    environment:
      MIGRATION_DSN: ${MIGRATION_DSN}
      MIGRATION_DIR: ./migrations
    restart: on-failure
    depends_on:
      - pg

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      GRPC_HOST: ${GRPC_HOST}
      GRPC_PORT: ${GRPC_PORT}
      PASSWORD_HASH_KEY: ${PASSWORD_HASH_KEY}
    restart: on-failure
    depends_on:
      - migrator

