// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Shemistan/grpc_user_api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Access is an autogenerated mock type for the Access type
type Access struct {
	mock.Mock
}

// AddAccess provides a mock function with given fields: ctx, req
func (_m *Access) AddAccess(ctx context.Context, req model.AccessRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AccessRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccess provides a mock function with given fields: ctx, req
func (_m *Access) GetAccess(ctx context.Context, req model.AccessRequest) (model.AccessRequest, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetAccess")
	}

	var r0 model.AccessRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AccessRequest) (model.AccessRequest, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AccessRequest) model.AccessRequest); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.AccessRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AccessRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllAccess provides a mock function with given fields: ctx
func (_m *Access) GetAllAccess(ctx context.Context) ([]model.AccessRequest, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAccess")
	}

	var r0 []model.AccessRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.AccessRequest, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.AccessRequest); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AccessRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAccess provides a mock function with given fields: ctx, req
func (_m *Access) UpdateAccess(ctx context.Context, req model.AccessRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AccessRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertAccess provides a mock function with given fields: ctx, req
func (_m *Access) UpsertAccess(ctx context.Context, req model.AccessRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AccessRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccess creates a new instance of Access. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *Access {
	mock := &Access{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
